<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>Alpha6FlightLab</AssemblyName>
    <Version>0.1.0</Version>
    <Company>Alpha 6 Designs</Company>
    <Product>Alpha 6 Flight Lab</Product>
    <ApplicationIcon>Assets/A6FL.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Alpha6Ops.Core/Alpha6Ops.Core.csproj" />
    <Resource Include="Assets/A6FL.ico" />
    <Resource Include="Assets/A6FL.png" />
  </ItemGroup>
</Project>
